// These tracks are commercial recordings owned by their respective labels.
// Before playing them on the site, confirm each videoId points to the rights
// holder's OWN YouTube upload with embedding enabled, and that you may use it.
// Adding a song is a one-line change; leave videoId empty until then.

export type Track = {
  id: string;
  title: string;
  artist: string;
  film?: string;
  year?: number;
  duration: number;
  videoId: string;
};

export type Playlist = {
  id: string;
  label: string;
  tracks: Track[];
};

export const playlists: Playlist[] = [
  {
    id: "the-adda",
    label: "The Adda",
    tracks: [
      { id: "n1", title: "Lag Ja Gale", artist: "Lata Mangeshkar", duration: 0, videoId: "fj4MnkljFXc" },
      { id: "n2", title: "Saibo (Lofi Flip)", artist: "Sony Music India", duration: 0, videoId: "Tpkv3jozpIw" },
      { id: "n3", title: "Chura Liya Hai Tumne Jo Dil Ko", artist: "Asha Bhosle", duration: 0, videoId: "XuCp0r3vhPQ" },
      { id: "n4", title: "Peele Peele O More Raja", artist: "Shemaroo Filmi Gaane", duration: 0, videoId: "ZAK8L8jQSeQ" },
      { id: "n5", title: "Brown Munde", artist: "AP Dhillon", duration: 0, videoId: "VNs_cCtdbPc" },
      { id: "n6", title: "Zhingat", artist: "Ajay Atul", duration: 0, videoId: "luhVm60Wiro" },
      { id: "n7", title: "Apsara Aali", artist: "Ajay Atul", duration: 0, videoId: "mW67u_hWiSo" },
      { id: "n8", title: "Iktara (Lofi Edit)", artist: "Sony Music India", duration: 0, videoId: "8V8dOlyQj4Y" },
      { id: "n9", title: "Hothon Se Chhu Lo Tum", artist: "Universal Music India", duration: 0, videoId: "1GdJS6J-fx8" },
      { id: "n10", title: "Sayonee", artist: "Junoon", duration: 0, videoId: "-8anr6et3Lw" },
      { id: "n11", title: "Tu Hi Meri Shab Hai", artist: "Vishesh Films", duration: 0, videoId: "mWBvudKcByg" },
      { id: "n12", title: "Zara Zara", artist: "Bombay Jayashri", duration: 0, videoId: "a71xD6RyOok" },
      { id: "n13", title: "Chithi Na Koi Sandesh", artist: "Jagjit Singh", duration: 0, videoId: "sBBzwoSngGg" },
      { id: "n14", title: "Tum Mile (Lofi Flip)", artist: "Sony Music India", duration: 0, videoId: "StUgCWSPU_k" },
      { id: "n15", title: "Kora Kagaz Tha Yeh Man Mera", artist: "Lata Mangeshkar", duration: 0, videoId: "kqXs4GGp8bw" },
      { id: "n16", title: "Badtameez Dil", artist: "Benny Dayal", duration: 0, videoId: "_FN96AOXsKY" },
      { id: "n17", title: "Navrai Majhi", artist: "Sunidhi Chauhan", duration: 0, videoId: "hEHNef66HT0" },
      { id: "n18", title: "Mera Pehla Pehla Pyaar", artist: "KK", duration: 0, videoId: "OW6LBjKvTpo" },
      { id: "n19", title: "Proper Patola", artist: "Badshah", duration: 0, videoId: "GVhmynWOPoM" },
      { id: "n20", title: "Dil Se Re", artist: "A.R. Rahman", duration: 0, videoId: "MYfaX0BH2AY" },
      { id: "n21", title: "Aao Huzoor Tumko", artist: "Asha Bhosle", duration: 0, videoId: "zGlGq14lClg" },
      { id: "n22", title: "Aaj Jane Ki Zid Na Karo", artist: "Farida Khanum", duration: 0, videoId: "KDJL2FyRDeA" },
      { id: "n23", title: "Tanha Dil", artist: "Shaan", duration: 0, videoId: "1Wm3NB6lYjs" },
      { id: "n24", title: "Galla Goodiyan", artist: "Shankar-Ehsaan-Loy", duration: 0, videoId: "jCEdTq3j-0U" },
      { id: "n25", title: "Khaabon Ke Parindey", artist: "Mohit Chauhan", duration: 0, videoId: "GbWKJ3rAgps" },
      { id: "n26", title: "Lamberghini", artist: "The Doorbeen", duration: 0, videoId: "5X7WWVTrBvM" },
      { id: "n27", title: "Gulabi Aankhen", artist: "Mohammed Rafi", duration: 0, videoId: "6Z3DO-OFIjQ" },
      { id: "n28", title: "Saathiya", artist: "Sonu Nigam", duration: 0, videoId: "eMA6GHTQ4WA" },
      { id: "n29", title: "Maeri", artist: "Euphoria", duration: 0, videoId: "KLe3ObP2EL0" },
      { id: "n30", title: "Sarkailo Khatiya", artist: "Kumar Sanu", duration: 0, videoId: "sdlOZxmOpBM" },
      { id: "n31", title: "Yaarana (Lofi Vibes)", artist: "Universal Music India", duration: 0, videoId: "Vg2-bbh-wX8" },
      { id: "n32", title: "Chandi Jaisa Rang", artist: "Pankaj Udhas", duration: 0, videoId: "6UiwXthbtZs" },
      { id: "n33", title: "Kombdi Palali", artist: "Ajay Atul", duration: 0, videoId: "2KaDL9TSja0" },
      { id: "n34", title: "Pehla Nasha", artist: "Udit Narayan", duration: 0, videoId: "iSUK1QoK9-E" },
      { id: "n35", title: "Deewane Hoke Hum", artist: "Kumar Sanu", duration: 0, videoId: "rdAA6u77id0" },
      { id: "n36", title: "Abhi Na Jao Chhod Kar", artist: "Mohammed Rafi", duration: 0, videoId: "oDfK3RfSlKk" },
      { id: "n37", title: "Urvashi Urvashi (Urasi Urasi)", artist: "A.R. Rahman", duration: 0, videoId: "WzLjRwdOJXg" },
      { id: "n38", title: "Ghar Aaja Soniya", artist: "Shazia Manzoor", duration: 0, videoId: "sT4GaJt3rWI" },
      { id: "n39", title: "Naah", artist: "Hardy Sandhu", duration: 0, videoId: "JitX0w0Squ8" },
      { id: "n40", title: "Jhilmil Sitaron Ka", artist: "Lata Mangeshkar", duration: 0, videoId: "MGyo_qC1kME" },
      { id: "n41", title: "Jhuki Jhuki Si Nazar", artist: "Jagjit Singh", duration: 0, videoId: "vf0au_2CYYE" },
      { id: "n42", title: "Hawayein", artist: "Arijit Singh", duration: 0, videoId: "lBACSadCKaQ" },
      { id: "n43", title: "Kya Surat Hai", artist: "Bombay Vikings", duration: 0, videoId: "h6g9EoxKAdw" },
      { id: "n44", title: "Billo Rani", artist: "Anand Raj Anand", duration: 0, videoId: "T15qhmhqraE" },
      { id: "n45", title: "Lahore", artist: "Guru Randhawa", duration: 0, videoId: "dZ0fwJojhrs" },
      { id: "n46", title: "Roz Roz Reshma", artist: "Bela Shende", duration: 0, videoId: "wwx41ypkJ2Q" },
      { id: "n47", title: "Shayad (Lofi Flip)", artist: "Sony Music India", duration: 0, videoId: "T3o4lncLJj8" },
      { id: "n48", title: "Huzur Is Kadar", artist: "Samir & Dipalee - India's Favorite Singing Couple", duration: 0, videoId: "rlqoxpXu7vw" },
      { id: "n49", title: "Yun Hi Chala Chal", artist: "T-Series Bollywood Classics", duration: 0, videoId: "eEeX2QMlSlo" },
      { id: "n50", title: "Purani Jeans", artist: "Ali Haider", duration: 0, videoId: "xcRLswiXTX4" },
      { id: "n51", title: "Illegal Weapon", artist: "Jasmine Sandlas", duration: 0, videoId: "ELepR_Sfjy4" },
      { id: "n52", title: "Ek Ladki Ko Dekha", artist: "Kumar Sanu", duration: 0, videoId: "htMvfOfixuM" },
      { id: "n53", title: "Woh Ladki Bahut Yaad Aati Hai", artist: "SongsWorld", duration: 0, videoId: "PLZUkp7rckA" },
      { id: "n54", title: "Chupke Chupke Raat Din", artist: "Ghulam Ali", duration: 0, videoId: "75VnN1dLA-Q" },
      { id: "n55", title: "Mahi Aaja", artist: "RDB", duration: 0, videoId: "_2Wloi2FwHE" },
      { id: "n56", title: "Chori Chori", artist: "Aneela", duration: 0, videoId: "O3SPAkCQ1a8" },
      { id: "n57", title: "Dolby Walya", artist: "Avinash Chebolu", duration: 0, videoId: "u6rKhw7nFbE" },
      { id: "n58", title: "In Dino (Lofi Remix)", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "yIyVhIspa2I" },
      { id: "n59", title: "Yeh Sham Mastani", artist: "Kishore Kumar", duration: 0, videoId: "1K6IjRZym7E" },
      { id: "n60", title: "Deewangi Deewangi", artist: "Rahat Fateh Ali Khan", duration: 0, videoId: "VzLG6OqOcn8" },
      { id: "n61", title: "Kya Karoon", artist: "Leslee Lewis", duration: 0, videoId: "nHCwoQk8ToA" },
      { id: "n62", title: "Wakhra Swag", artist: "Times Music", duration: 0, videoId: "iMdH_G4N9nY" },
      { id: "n63", title: "Jivrang (Marathi)", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "en60_iC0u2M" },
      { id: "n64", title: "Awara (Lofi Loop)", artist: "ᴘᴀʀᴀʟʟᴇʟ  ᴜɴɪᴠᴇʀsᴇ", duration: 0, videoId: "F4EKWu1_h0Y" },
      { id: "n65", title: "Koi Fariyaad", artist: "Jagjit Singh", duration: 0, videoId: "8MN2bxMiB9A" },
      { id: "n66", title: "Roop Tera Mastana", artist: "Kishore Kumar", duration: 0, videoId: "zbvfAkJWntc" },
      { id: "n67", title: "Whole Month", artist: "Guri Lahoria", duration: 0, videoId: "c32pPHqscl8" },
      { id: "n68", title: "Suno Aisha", artist: "Amit Trivedi", duration: 0, videoId: "fAzO3s7Dgnw" },
      { id: "n69", title: "Matzha Malhar", artist: "Ajay Atul", duration: 0, videoId: "qIUVmFAxodU" },
      { id: "n70", title: "Raanjhanaa (Lofi Edit)", artist: "Silent Ocean", duration: 0, videoId: "fUi10a4fHps" },
      { id: "n71", title: "Mere Bina", artist: "Pritam", duration: 0, videoId: "XvUSsh3gdO4" },
      { id: "n72", title: "Chura Liya (Lofi Remake)", artist: "Saregama Mix Station", duration: 0, videoId: "0ZlSSx8Tr3Q" },
      { id: "n73", title: "Khamoshiyan", artist: "Arijit Singh", duration: 0, videoId: "Mv3SZDP7QUo" },
      { id: "n74", title: "Na Ja", artist: "Pav Dharia", duration: 0, videoId: "Q-GOFPM01d0" },
      { id: "n75", title: "Saibo", artist: "Shreya Ghoshal", duration: 0, videoId: "9Bmh6vaQt0s" },
      { id: "n76", title: "Mera Dil Bhi Kitna Pagal Hai", artist: "Ishtar Music", duration: 0, videoId: "RVQsBlI35vw" },
      { id: "n77", title: "Baat Niklegi To Phir", artist: "Mehdi Hassan", duration: 0, videoId: "IhFimj8IsmU" },
      { id: "n78", title: "Kaho Na Pyaar Hai", artist: "Udit Narayan", duration: 0, videoId: "-LESbtPT8uw" },
      { id: "n79", title: "Abhang Fusion (Marathi)", artist: "Fusion Vibes Studioo", duration: 0, videoId: "TlHHe1zDkQk" },
      { id: "n80", title: "Pappu Can't Dance", artist: "Benny Dayal", duration: 0, videoId: "dbdtBQ16CXc" },
      { id: "n81", title: "Ya Ali", artist: "Zubeen Garg", duration: 0, videoId: "pmHnlBqjpm0" },
      { id: "n82", title: "Sajan Ghar Aaye", artist: "Sony Music India", duration: 0, videoId: "8XtXLVylOoU" },
      { id: "n83", title: "Kali Kali Aankhen (Lofi)", artist: "Ishtar Music", duration: 0, videoId: "fE8iP7n-W4c" },
      { id: "n84", title: "Chaudhvin Ka Chand", artist: "Mohammed Rafi", duration: 0, videoId: "uEgnjhIK9sc" },
      { id: "n85", title: "Bheegi Bheegi Raaton Mein", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "VLIgq8nsfis" },
      { id: "n86", title: "Zindagi Ke Safar Mein", artist: "Kishore Kumar", duration: 0, videoId: "eWyYqYLNNuY" },
      { id: "n87", title: "Chitthi Aai Hai", artist: "Pankaj Udhas", duration: 0, videoId: "S6Mk-hY-vjw" },
      { id: "n88", title: "Sairat Zaala Ji", artist: "Ajay Atul", duration: 0, videoId: "ZL3MnrnLLpo" },
      { id: "n89", title: "Mehrama (Lofi version)", artist: "Sony Music India", duration: 0, videoId: "NQro51k_8AE" },
      { id: "n90", title: "Babuji Dheere Chalna", artist: "S D Burman", duration: 0, videoId: "MWrTXyGloKE" },
      { id: "n91", title: "Gur Nalo Ishq Mitha", artist: "Bally Sagoo", duration: 0, videoId: "VL4p2oYvgEU" },
      { id: "n92", title: "Jashne Bahara (Lofi)", artist: "LOFI Moonlight", duration: 0, videoId: "I3-X8Au_eKk" },
      { id: "n93", title: "Gham Ka Khazana", artist: "Ghulam Ali", duration: 0, videoId: "fSFJdaJjeLM" },
      { id: "n94", title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh", duration: 0, videoId: "lZLxjLYyhYQ" },
      { id: "n95", title: "Saada Kutta Kutta", artist: "Tuada Kutta Tommy", duration: 0, videoId: "Pv5cbwIhGdE" },
      { id: "n96", title: "Olya Sanjveli (Marathi)", artist: "Everest Marathi and Avinash Vishwajeet official", duration: 0, videoId: "iTYp4qBFXcQ" },
      { id: "n97", title: "Pehla Nasha (Lofi Flip)", artist: "Saregama Mix Station", duration: 0, videoId: "zM6z-RhMMI4" },
      { id: "n98", title: "Pyaar Ka Pehla Khat", artist: "Hindi Ghazal Hits", duration: 0, videoId: "kZcR4GZrpoo" },
      { id: "n99", title: "Zara Sa (Lofi Version)", artist: "Sony Music India", duration: 0, videoId: "-8C_2BBVWk8" },
      { id: "n100", title: "Kajra Re", artist: "Alisha Chinai", duration: 0, videoId: "tGv6Ce9mMWA" },
      { id: "n101", title: "Kya Hua Tera Wada", artist: "Mohammed Rafi", duration: 0, videoId: "cIVkYSm7Orw" },
      { id: "n102", title: "Na Tum Jano Na Hum", artist: "Lata Mangeshkar", duration: 0, videoId: "eSxo4l-epv8" },
      { id: "n103", title: "Jind Mahi", artist: "Gippy Grewal", duration: 0, videoId: "gfYXKP5V-Tc" },
      { id: "n104", title: "Hridayi Vasant (Marathi)", artist: "NH Marathi", duration: 0, videoId: "ZsXH5AFvYxk" },
      { id: "n105", title: "Ranjha (Lofi Flip)", artist: "Sony Music India", duration: 0, videoId: "V7LwfY5U5WI" },
      { id: "n106", title: "Ahista Ahista Ghazal", artist: "Saregama Ghazal", duration: 0, videoId: "vukyvBndFR8" },
      { id: "n107", title: "Dus Bahane", artist: "Vishal Dadlani", duration: 0, videoId: "mIWpsOjQNDw" },
      { id: "n108", title: "Mundian To Bach Ke", artist: "Panjabi MC", duration: 0, videoId: "H2gmeNH_oZ0" },
      { id: "n109", title: "Aaye Ho Meri Zindagi Mein", artist: "Lata Mangeshkar", duration: 0, videoId: "7uOSdDXmhnM" },
      { id: "n110", title: "Hosanna (Lofi Mix)", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "dfNdRsNSFx4" },
      { id: "n111", title: "Hangover", artist: "Yo Yo Honey Singh", duration: 0, videoId: "1gqBb4Y7LJA" },
      { id: "n112", title: "Ti Sadhya Kay Karte (Marathi)", artist: "Rajshri Marathi", duration: 0, videoId: "It3Gp7XdWv0" },
      { id: "n113", title: "Kisi Nazar Ko Tera Intezar", artist: "Amitabh Bachchan", duration: 0, videoId: "7ub8DyewfHg" },
      { id: "n114", title: "Lift Karade", artist: "Yo Yo Honey Singh", duration: 0, videoId: "IU2ttJ73h2Y" },
      { id: "n115", title: "Sauda Khara Khara", artist: "Diljit Dosanjh", duration: 0, videoId: "LYEqeUr-158" },
      { id: "n116", title: "Mitwa (Lofi Flip)", artist: "Sony Music India", duration: 0, videoId: "ru_5PA8cwkE" },
      { id: "n117", title: "Mora Saiyan", artist: "Sukhwinder Singh", duration: 0, videoId: "xeUUBEqR16w" },
      { id: "n118", title: "Ek Din Aap (Lofi)", artist: "Sanju ", duration: 0, videoId: "1sRaLqtHXQU" },
      { id: "n119", title: "Sarakti Jaye Hai", artist: "Chitra Singh", duration: 0, videoId: "3YkhPYtMi4c" },
      { id: "n120", title: "Jeene Laga Hoon", artist: "Atif Aslam", duration: 0, videoId: "pkzOBl1p7y4" },
      { id: "n121", title: "Mala Ved Laagale", artist: "Ajay Atul", duration: 0, videoId: "Pf3SVdsdBfo" },
      { id: "n122", title: "Tujhe Sochta Hoon (Lofi)", artist: "Sony Music India", duration: 0, videoId: "PkhfKq9m0Uo" },
      { id: "n123", title: "Parda Hai Parda", artist: "Aziz Nazan", duration: 0, videoId: "Ch-i9iBrCYQ" },
      { id: "n124", title: "Abhi Toh Party Shuru Hui Hai", artist: "Badshah", duration: 0, videoId: "-F63hH7MlRY" },
      { id: "n125", title: "Soniyo (Lofi Flip)", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "SAQ74fZp2Ts" },
      { id: "n126", title: "Apne Honton Par Sajana", artist: "Lata Mangeshkar", duration: 0, videoId: "_HF0o9NZ7w0" },
      { id: "n127", title: "Allah Ke Bande", artist: "Kailash Kher", duration: 0, videoId: "lph2oHvfNPU" },
      { id: "n128", title: "Jaguar", artist: "Yo Yo Honey Singh", duration: 0, videoId: "i2GC06euEDE" },
      { id: "n129", title: "Gulabi (Marathi Movie Theme)", artist: "Gulabi", duration: 0, videoId: "f9PF6zH3Ijg" },
      { id: "n130", title: "Dil Ibaadat (Lofi)", artist: "LyricGuruVEVO", duration: 0, videoId: "xm-4SZxjlzU" },
      { id: "n131", title: "Likhe Jo Khat Tujhe", artist: "Mohammed Rafi", duration: 0, videoId: "y_m0b20u5oQ" },
      { id: "n132", title: "Gulaabo", artist: "Shaan", duration: 0, videoId: "bUTdUaVmj8o" },
      { id: "n133", title: "Tera Zikr (Lofi Version)", artist: "Sony Music India", duration: 0, videoId: "eK0IIyBlYew" },
      { id: "n134", title: "Awari", artist: "Atif Aslam", duration: 0, videoId: "-S1IhJ_DHjw" },
      { id: "n135", title: "Naag", artist: "Sidhu Moose Wala", duration: 0, videoId: "MyYAglA_Cdk" },
      { id: "n136", title: "Gondhal Fusion", artist: "Ajay Atul", duration: 0, videoId: "2pVK0kxgfE4" },
      { id: "n137", title: "Chupke Chupke (Pankaj Udhas)", artist: "Saregama Ghazal", duration: 0, videoId: "MWjaK_nW72E" },
      { id: "n138", title: "Chaka Chak", artist: "A.R. Rahman", duration: 0, videoId: "Kz5uJlucE5Q" },
      { id: "n139", title: "Haare Haare (Lofi Remix)", artist: "Ishtar Music", duration: 0, videoId: "23z6HhoPBrA" },
      { id: "n140", title: "Aane Wala Pal", artist: "Kishore Kumar", duration: 0, videoId: "tIJBsWXJdhs" },
      { id: "n141", title: "Naam Hai Tera Tera", artist: "Pop Chartbusters", duration: 0, videoId: "DULrvDVqyXI" },
      { id: "n142", title: "Coka", artist: "Guru Randhawa", duration: 0, videoId: "7lWeQs8Firo" },
      { id: "n143", title: "Dhaga Dhaga (Marathi)", artist: "Saregama Marathi", duration: 0, videoId: "sUkTlyPF-80" },
      { id: "n144", title: "Kal Ho Naa Ho (Lofi Flip)", artist: "Sonu Nigam", duration: 0, videoId: "oq5Ocx_rEv8" },
      { id: "n145", title: "Karoge Yaad To", artist: "Jagjit Singh", duration: 0, videoId: "ieywRmgkrkg" },
      { id: "n146", title: "Hookah Bar", artist: "Himesh Reshammiya", duration: 0, videoId: "EvMKzUCifiU" },
      { id: "n147", title: "Khaab", artist: "Ammy Virk", duration: 0, videoId: "GJ-olNB3P7Y" },
      { id: "n148", title: "Manjha", artist: "Vishal Mishra", duration: 0, videoId: "YKcmMmJlKNk" },
      { id: "n149", title: "Sajaa De Ghar (Lofi)", artist: "Nova Spiritual India", duration: 0, videoId: "1_u-Koe8aog" },
      { id: "n150", title: "Safar Mein Dhoop To Hogi", artist: "Mohammed Rafi", duration: 0, videoId: "e6izN8Y-eDc" },
      { id: "n151", title: "Chura Liya Hai (Original)", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "0vTmfTTGJZA" },
      { id: "n152", title: "Wajle Ki Bara", artist: "Ajay Atul", duration: 0, videoId: "7R7QJkznJGU" },
      { id: "n153", title: "Satisfya", artist: "Imran Khan", duration: 0, videoId: "sJfR4UswX2k" },
      { id: "n154", title: "Jab Koi Baat (Lofi Mix)", artist: "Ishtar Music", duration: 0, videoId: "rFU28HBP7B0" },
      { id: "n155", title: "Subah Subah", artist: "Sona Mohapatra", duration: 0, videoId: "T7HZS3nJdRo" },
      { id: "n156", title: "Deewane To Deewane Hain", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "oiq_KkEshSg" },
      { id: "n157", title: "Yeh Raaten Yeh Mausam", artist: "Kishore Kumar & Asha Bhosle", duration: 0, videoId: "ouNb2s33ioQ" },
      { id: "n158", title: "Hangama Hai Kyon Barpa", artist: "Ghulam Ali", duration: 0, videoId: "Wwy2F76XzJc" },
      { id: "n159", title: "Dil Chhota Sa (Chhoti Si Aasha)", artist: "A.R. Rahman", duration: 0, videoId: "P2s1Cl23oik" },
      { id: "n160", title: "Daku (Daaku)", artist: "Gurlez Akhtar", duration: 0, videoId: "1E9vYjuQfOA" },
      { id: "n161", title: "Aankh Hai Bhari Bhari 2.0", artist: "Ishtar Music", duration: 0, videoId: "PZz0t4YINA4" },
      { id: "n162", title: "Gore Gore Mukhde Pe", artist: "Kavita Krishnamurthy", duration: 0, videoId: "sRoWL8EZ3k8" },
      { id: "n163", title: "Dil Cheez Kya Hai", artist: "Asha Bhosle", duration: 0, videoId: "hfsGt3R0To8" },
      { id: "n164", title: "Tere Khushboo Mein Base Khat", artist: "Jagjit Singh", duration: 0, videoId: "k2iHLR3_Swk" },
      { id: "n165", title: "Ho Gaya Hai Tujhko Toh Pyar", artist: "Atif Aslam", duration: 0, videoId: "hw_HpTI_Wkw" },
      { id: "n166", title: "Billo Thumka Ji", artist: "Hasan Jahangir", duration: 0, videoId: "vuWuUxhvz34" },
      { id: "n167", title: "Kabhi Alvida Naa Kehna (Lofi)", artist: "SonyMusicIndiaVEVO", duration: 0, videoId: "O8fIwHfZz2E" },
      { id: "n168", title: "Abhi Na Jao (Remix)", artist: "Saregama Music", duration: 0, videoId: "prYPG-05udg" },
      { id: "n169", title: "Ye Bata De Lofi", artist: "Chitra Singh", duration: 0, videoId: "9RefrYQjG_Y" },
      { id: "n170", title: "Kombdi Palali (Original Remix)", artist: "The Mastering Project", duration: 0, videoId: "bGo6X71kocI" },
      { id: "n171", title: "Excuses", artist: "AP Dhillon", duration: 0, videoId: "vX2cDW8LUWk" },
      { id: "n172", title: "Main Koi Aisa Geet Gaoon (Lofi)", artist: "LYRICAL BAM HINDI", duration: 0, videoId: "uue4MyYaFps" },
      { id: "n173", title: "Dil Mera Churaya Kyun (Lofi)", artist: "Ishtar Music", duration: 0, videoId: "JdDEVROAKjg" },
      { id: "n174", title: "Sarkailo Khatiya (Remix)", artist: "DJ SANU MUMBAI", duration: 0, videoId: "VBua4cCGfeE" },
      { id: "n175", title: "Chandi Jaisa Rang (Live Track)", artist: "Pankaj Udhas", duration: 0, videoId: "__yrM3luls0" },
      { id: "n176", title: "Tumhe Jo Maine Dekha", artist: "Mohit Chauhan", duration: 0, videoId: "79rgnxESrS8" },
      { id: "n177", title: "Rishte Naate (Lofi)", artist: "AB Lofi", duration: 0, videoId: "0jTmjiWs81o" },
      { id: "s1", title: "Dil Diyan Gallan", artist: "Atif Aslam", film: "Tiger Zinda Hai", year: 2017, duration: 0, videoId: "SAcpESN_Fk4" },
      { id: "s2", title: "High Rated Gabru", artist: "Guru Randhawa", duration: 0, videoId: "hjWf8A0YNSE" },
      { id: "s3", title: "Amplifier", artist: "Imran Khan", duration: 0, videoId: "uuCFRaFWjwY" },
      { id: "s4", title: "Kabira", artist: "Tochi Raina & Rekha Bhardwaj", film: "Yeh Jawaani Hai Deewani", year: 2013, duration: 0, videoId: "jHNNMj5bNQw" },
      { id: "s5", title: "Kun Faya Kun", artist: "A.R. Rahman, Javed Ali & Mohit Chauhan", film: "Rockstar", year: 2011, duration: 0, videoId: "T94PHkuydcw" },
      { id: "s6", title: "Tum Se Hi", artist: "Mohit Chauhan", film: "Jab We Met", year: 2007, duration: 0, videoId: "mt9xg0mmt28" },
      { id: "s7", title: "Pyaar Ke Pal", artist: "KK", duration: 0, videoId: "ndU9kBk3UWI" },
      { id: "s8", title: "Zingaat", artist: "Ajay-Atul", film: "Sairat", year: 2016, duration: 0, videoId: "g8bTNID9nPs" },
      { id: "s9", title: "Dooba Dooba", artist: "Silk Route", duration: 0, videoId: "epUBGOngvaU" },
      { id: "s10", title: "O Sanam", artist: "Lucky Ali", duration: 0, videoId: "cADnAAsYlqM" },
      { id: "s11", title: "Woh Chali Woh Chali", artist: "Bombay Vikings", duration: 0, videoId: "bOL3vqJ1IH0" },
      { id: "s12", title: "Made In India", artist: "Alisha Chinai", duration: 0, videoId: "_rGo1s6iEjc" },
      { id: "s13", title: "Baba Deewana", artist: "Baba Sehgal", film: "Main Bhi Madonna", duration: 0, videoId: "SgZBe16-C6o" },
      { id: "s14", title: "Ho Jayegi Balle Balle", artist: "Daler Mehndi", duration: 0, videoId: "V39meB3T2ek" },
      { id: "s15", title: "Best Indian LoFi Vol. 2 (Saibo · Iktara · Tum Mile · Raanjhanaa)", artist: "Sony Music India", duration: 0, videoId: "0m1VFNQFVew" },
      { id: "s16", title: "Best #LoFi Songs Collection (Dil Se Re · Chura Liya · …)", artist: "Ishtar Music", duration: 0, videoId: "hMFYC2lKVC8" },
      { id: "s17", title: "Ghazal-e-LoFi Vol. 1 (Chithi Na Koi Sandesh · Tum Itna Jo…)", artist: "Jagjit Singh · Saregama", duration: 0, videoId: "3t3JSH-yXas" },
    ],
  },
];

export const playablePlaylists: Playlist[] = playlists
  .map((playlist) => ({
    ...playlist,
    tracks: playlist.tracks.filter((track) => track.videoId !== ""),
  }))
  .filter((playlist) => playlist.tracks.length > 0);
